
package com.heliumv.hello.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.4
 * Thu Apr 04 12:04:14 CEST 2013
 * Generated source version: 2.7.4
 */

@XmlRootElement(name = "whatIsTheAnswer", namespace = "http://hello.heliumv.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "whatIsTheAnswer", namespace = "http://hello.heliumv.com/")

public class WhatIsTheAnswer {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

