
package com.heliumv.hello.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.4
 * Thu Apr 04 12:04:14 CEST 2013
 * Generated source version: 2.7.4
 */

@XmlRootElement(name = "whatIsTheAnswerResponse", namespace = "http://hello.heliumv.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "whatIsTheAnswerResponse", namespace = "http://hello.heliumv.com/")

public class WhatIsTheAnswerResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

